import { useEffect, useRef, useState, useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { LWWMap } from 'crdt-core';

export function useSync(roomId) {
  const clientId = useRef(uuidv4()).current;
  const [shapes, setShapes] = useState({});
  const [cursors, setCursors] = useState({});
  const ws = useRef(null);
  const crdt = useRef(new LWWMap(clientId));

  const connect = useCallback(() => {
    // Force port 3001 for local server
    const host = window.location.hostname === 'localhost' ? 'localhost:3001' : window.location.host;
    const url = `ws://${host}/?room=${roomId}&clientId=${clientId}`;
    
    ws.current = new WebSocket(url);

    ws.current.onopen = () => {
      console.log('Connected to sync server');
    };

    ws.current.onmessage = (event) => {
      const data = JSON.parse(event.data);

      if (data.type === 'baseline') {
        crdt.current = new LWWMap(clientId, data.state);
        setShapes(crdt.current.get());
      } else if (data.type === 'delta') {
        // Check if this delta was generated by this exact client (an echo)
        let isEcho = false;
        for (const shapeId in data.delta) {
          const shapeMeta = data.delta[shapeId].meta;
          for (const key in shapeMeta) {
            if (shapeMeta[key].clientId === clientId) {
              isEcho = true;
              break;
            }
          }
        }

        crdt.current.merge(data.delta);
        
        // If it's an echo, we already applied it locally optimistically, so skip re-rendering
        // to prevent react-konva from jittering during active drags.
        if (!isEcho) {
          setShapes(crdt.current.get());
        }
      } else if (data.type === 'cursor') {
        if (data.clientId !== clientId) {
          setCursors(prev => ({ ...prev, [data.clientId]: data }));
        }
      }
    };

    ws.current.onclose = () => {
      console.log('Disconnected from sync server, retrying in 2s...');
      setTimeout(connect, 2000);
    };
  }, [roomId, clientId]);

  useEffect(() => {
    connect();
    return () => {
      if (ws.current) {
        ws.current.onclose = null;
        ws.current.close();
      }
    };
  }, [connect]);

  const undoStack = useRef([]);
  const redoStack = useRef([]);

  // Optimistic update + Delta Broadcast
  const updateShape = useCallback((shapeId, updates, isUndoRedoAction = false, skipUndo = false) => {
    const time = Date.now();
    const delta = { [shapeId]: { data: {}, meta: {} } };

    // Record for undo stack
    if (!isUndoRedoAction && !skipUndo) {
      const currentState = crdt.current.state[shapeId]?.data || {};
      const previousState = {};
      let hasChanges = false;
      Object.entries(updates).forEach(([key, value]) => {
        if (currentState[key] !== value) {
          previousState[key] = currentState[key] !== undefined ? currentState[key] : null;
          hasChanges = true;
        }
      });
      
      if (hasChanges) {
        const lastAction = undoStack.current[undoStack.current.length - 1];
        if (lastAction && lastAction.shapeId === shapeId && (Date.now() - lastAction.time < 1000)) {
          // Coalesce continuous actions (e.g., color picker dragging)
          lastAction.newState = { ...lastAction.newState, ...updates };
          lastAction.time = Date.now();
          // We intentionally DO NOT update lastAction.previousState so we can revert to the true original
        } else {
          undoStack.current.push({ shapeId, previousState, newState: updates, time: Date.now() });
        }
        redoStack.current = []; // clear redo stack on new action
      }
    }

    // 1. Optimistic Local Update
    Object.entries(updates).forEach(([key, value]) => {
      const finalTimestamp = crdt.current.set(shapeId, key, value, time);
      if (finalTimestamp !== null) {
        delta[shapeId].data[key] = value;
        delta[shapeId].meta[key] = { timestamp: finalTimestamp, clientId };
      }
    });

    // Only broadcast if we actually had valid updates
    if (Object.keys(delta[shapeId].data).length === 0) return;

    setShapes(crdt.current.get());

    // 2. Broadcast Delta
    if (ws.current && ws.current.readyState === WebSocket.OPEN) {
      ws.current.send(JSON.stringify({ type: 'delta', delta }));
    }
  }, [clientId]);

  const pushUndo = useCallback((shapeId, previousState, newState) => {
    undoStack.current.push({ shapeId, previousState, newState });
    redoStack.current = [];
  }, []);

  const undo = useCallback(() => {
    if (undoStack.current.length === 0) return;
    const action = undoStack.current.pop();
    redoStack.current.push(action);
    
    // If it was a creation (all previous states were null), undo = delete
    const isCreation = Object.values(action.previousState).every(v => v === null);
    if (isCreation) {
      updateShape(action.shapeId, { _deleted: true }, true);
    } else {
      const revert = {};
      for (const [k, v] of Object.entries(action.previousState)) {
        if (v !== null) revert[k] = v;
      }
      if (Object.keys(revert).length > 0) {
        updateShape(action.shapeId, revert, true);
      }
    }
  }, [updateShape]);

  const redo = useCallback(() => {
    if (redoStack.current.length === 0) return;
    const action = redoStack.current.pop();
    undoStack.current.push(action);
    updateShape(action.shapeId, action.newState, true);
  }, [updateShape]);

  const clearAll = useCallback(() => {
    const currentShapes = crdt.current.get();
    Object.keys(currentShapes).forEach(shapeId => {
      if (!currentShapes[shapeId]._deleted) {
        updateShape(shapeId, { _deleted: true }, true); // pass true to prevent individual deletes filling stack
      }
    });
    
    // Clear stacks on Clear All
    undoStack.current = [];
    redoStack.current = [];
  }, [updateShape]);

  const updateCursor = useCallback((x, y) => {
    if (ws.current && ws.current.readyState === WebSocket.OPEN) {
      ws.current.send(JSON.stringify({ type: 'cursor', clientId, x, y, timestamp: Date.now() }));
    }
  }, [clientId]);

  const addShape = useCallback((type, x, y, width, height, color) => {
    const shapeId = uuidv4();
    updateShape(shapeId, { type, x, y, width, height, color });
  }, [updateShape]);

  return { shapes, cursors, updateShape, updateCursor, addShape, clientId, undo, redo, clearAll, undoStack, redoStack, pushUndo };
}
