import { useEffect, useRef, useState, useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { LWWMap } from 'crdt-core';

export function useSync(roomId) {
  const clientId = useRef(uuidv4()).current;
  const [shapes, setShapes] = useState({});
  const [cursors, setCursors] = useState({});
  const ws = useRef(null);
  const crdt = useRef(new LWWMap(clientId));

  const connect = useCallback(() => {
    // Force port 3001 for local server
    const host = window.location.hostname === 'localhost' ? 'localhost:3001' : window.location.host;
    const url = `ws://${host}/?room=${roomId}&clientId=${clientId}`;
    
    ws.current = new WebSocket(url);

    ws.current.onopen = () => {
      console.log('Connected to sync server');
    };

    ws.current.onmessage = (event) => {
      const data = JSON.parse(event.data);

      if (data.type === 'baseline') {
        crdt.current = new LWWMap(clientId, data.state);
        setShapes(crdt.current.get());
      } else if (data.type === 'delta') {
        // Check if this delta was generated by this exact client (an echo)
        let isEcho = false;
        for (const shapeId in data.delta) {
          const shapeMeta = data.delta[shapeId].meta;
          for (const key in shapeMeta) {
            if (shapeMeta[key].clientId === clientId) {
              isEcho = true;
              break;
            }
          }
        }

        crdt.current.merge(data.delta);
        
        // If it's an echo, we already applied it locally optimistically, so skip re-rendering
        // to prevent react-konva from jittering during active drags.
        if (!isEcho) {
          setShapes(crdt.current.get());
        }
      } else if (data.type === 'cursor') {
        if (data.clientId !== clientId) {
          setCursors(prev => ({ ...prev, [data.clientId]: data }));
        }
      }
    };

    ws.current.onclose = () => {
      console.log('Disconnected from sync server, retrying in 2s...');
      setTimeout(connect, 2000);
    };
  }, [roomId, clientId]);

  useEffect(() => {
    connect();
    return () => {
      if (ws.current) {
        ws.current.onclose = null;
        ws.current.close();
      }
    };
  }, [connect]);

  // Optimistic update + Delta Broadcast
  const updateShape = useCallback((shapeId, updates) => {
    const time = Date.now();
    const delta = { [shapeId]: { data: {}, meta: {} } };

    // 1. Optimistic Local Update
    Object.entries(updates).forEach(([key, value]) => {
      const finalTimestamp = crdt.current.set(shapeId, key, value, time);
      if (finalTimestamp !== null) {
        delta[shapeId].data[key] = value;
        delta[shapeId].meta[key] = { timestamp: finalTimestamp, clientId };
      }
    });

    // Only broadcast if we actually had valid updates
    if (Object.keys(delta[shapeId].data).length === 0) return;

    setShapes(crdt.current.get());

    // 2. Broadcast Delta
    if (ws.current && ws.current.readyState === WebSocket.OPEN) {
      ws.current.send(JSON.stringify({ type: 'delta', delta }));
    }
  }, [clientId]);

  const updateCursor = useCallback((x, y) => {
    if (ws.current && ws.current.readyState === WebSocket.OPEN) {
      ws.current.send(JSON.stringify({ type: 'cursor', clientId, x, y, timestamp: Date.now() }));
    }
  }, [clientId]);

  const addShape = useCallback((type, x, y, width, height, color) => {
    const shapeId = uuidv4();
    updateShape(shapeId, { type, x, y, width, height, color });
  }, [updateShape]);

  return { shapes, cursors, updateShape, updateCursor, addShape, clientId };
}
